In [ ]:
import numpy as np
import pandas as pd

pateints=pd.read_csv(r"IndividualDetails.csv")
total=pateints.shape[0]
active=pateints.query("current_status=='Hospitalized'").shape[0]
recovered=pateints.query("current_status=='Recovered'").shape[0]
death=pateints.query("current_status=='Deceased'").shape[0]

30

In [2]:
pateints.sample(20)

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
62,62,NaN,10/03/2020,85,M,Jaipur,Jaipur,Rajasthan,India,Recovered,10/03/2020,Travelled from Dubai
4607,4607,NaN,06/04/2020,NaN,NaN,NaN,Mumbai,Maharashtra,NaN,Hospitalized,06/04/2020,Details awaited
2577,2577,NaN,03/04/2020,NaN,NaN,NaN,Visakhapatnam,Andhra Pradesh,NaN,Hospitalized,03/04/2020,NaN
581,581,NaN,25/03/2020,NaN,NaN,Sangli,Sangli,Maharashtra,NaN,Hospitalized,25/03/2020,Details awaited
7172,7173,NaN,10/04/2020,NaN,NaN,NaN,NaN,Delhi,NaN,Hospitalized,10/04/2020,Details awaited
6083,6084,NaN,09/04/2020,NaN,NaN,NaN,Mumbai,Maharashtra,NaN,Hospitalized,09/04/2020,Details awaited
1796,1796,TN-P212,01/04/2020,60,M,Bodi,Theni,Tamil Nadu,NaN,Hospitalized,01/04/2020,Travelled to Delhi
167,167,TS-P12,18/03/2020,NaN,NaN,Hyderabad,Hyderabad,Telangana,Indonesia,Hospitalized,18/03/2020,Indonesian
2918,2918,NaN,03/04/2020,NaN,NaN,NaN,NaN,Telangana,NaN,Hospitalized,03/04/2020,Details awaited
1009,1009,NaN,28/03/2020,NaN,NaN,NaN,NaN,Telangana,NaN,Hospitalized,28/03/2020,Details awaited
1025,1025,NaN,28/03/2020,48,M,NaN,Indore,Madhya Pradesh,NaN,Hospitalized,28/03/2020,contacts of earlier positive cases of #COVID19...
6157,6158,NaN,09/04/2020,NaN,NaN,NaN,Mumbai,Maharashtra,NaN,Hospitalized,09/04/2020,Details awaited
194,194,NaN,19/03/2020,NaN,F,Jaipur,Jaipur,Rajasthan,India,Hospitalized,19/03/2020,Travelled from Spain via Dubai - New Delhi on ...
1543,1543,TN-P109,31/03/2020,NaN,M,NaN,Namakkal,Tamil Nadu,NaN,Hospitalized,31/03/2020,Travelled to Delhi
396,396,AP-P6,22/03/2020,49,F,Visakhapatnam,Visakhapatnam,Andhra Pradesh,India,Hospitalized,22/03/2020,Patient's husband tested positive
4228,4228,NaN,05/04/2020,NaN,NaN,NaN,Hyderabad,Telangana,NaN,Hospitalized,05/04/2020,Details Awaited
3369,3369,NaN,04/04/2020,NaN,NaN,NaN,Mahrajganj,Uttar Pradesh,NaN,Hospitalized,04/04/2020,Travelled to Delhi
6342,6343,TN-P792,09/04/2020,NaN,M,NaN,Namakkal,Tamil Nadu,NaN,Hospitalized,09/04/2020,Details awaited
8,8,NaN,04/03/2020,55,NaN,Gurugram,Italians*,Haryana,Italy,Recovered,29/03/2020,Travelled from Italy
5022,5023,NaN,07/04/2020,NaN,NaN,NaN,Nuh,Haryana,NaN,Hospitalized,07/04/2020,Details awaited